"""univer fields changed

Revision ID: b368454cae46
Revises: 3295c827f34b
Create Date: 2025-04-13 22:39:48.491274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b368454cae46'
down_revision: Union[str, None] = '3295c827f34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('country_name', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('cover_image', sa.String(length=255), nullable=True))
    op.add_column('universities', sa.Column('scholarship_name', sa.String(length=255), nullable=True))
    op.add_column('universities', sa.Column('scholarship_description', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('scholarship_benefits', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('universities', sa.Column('application_steps', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('universities', 'admissions')
    op.drop_column('universities', 'scholarships')
    op.drop_column('universities', 'applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('applications', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('scholarships', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('admissions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('universities', 'application_steps')
    op.drop_column('universities', 'scholarship_benefits')
    op.drop_column('universities', 'scholarship_description')
    op.drop_column('universities', 'scholarship_name')
    op.drop_column('universities', 'cover_image')
    op.drop_column('universities', 'country_name')
    # ### end Alembic commands ###
